CREATE TABLE dbo.Games (
    GameID INT NOT NULL IDENTITY
    ,CONSTRAINT PK_Games PRIMARY KEY (GameID)

    ,Team1Score INT NOT NULL
    ,Team2Score INT NOT NULL
    ,GameDate DATETIME2 NOT NULL

    ,AddDate DATETIME2 NOT NULL
        CONSTRAINT DF_Games_AddDate DEFAULT (SYSUTCDATETIME())
    
    ,_StartDateTime DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL
    ,_EndDateTime DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL

    ,PERIOD FOR SYSTEM_TIME (_StartDateTime, _EndDateTime)
    ,MostValuablePlayer NVARCHAR(100) NULL
) WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE = dbo.GamesHistory));
GO
