IF OBJECT_ID('dbo.Apps') IS NOT NULL
	DROP TABLE dbo.Apps;
GO


-- Wrong way:
CREATE TABLE dbo.Apps (
	AppID UNIQUEIDENTIFIER NOT NULL
		CONSTRAINT DF_Apps_AppID DEFAULT (NEWID())
	,CONSTRAINT PK_Apps PRIMARY KEY CLUSTERED (AppID)

	,AppName NVARCHAR(100) NOT NULL
	,INDEX IX_Apps_AppName (AppName)

	,CreateDate DATETIME2 NOT NULL
		CONSTRAINT DF_Apps_AppName DEFAULT (SYSUTCDATETIME())
	,INDEX IX_Apps_CreateDate (CreateDate)
);
GO

-- Right way:
CREATE TABLE dbo.Apps (
	CX INT NOT NULL IDENTITY
	,INDEX IX_Apps_CX CLUSTERED (CX)
	
	,AppID UNIQUEIDENTIFIER NOT NULL
		CONSTRAINT DF_Apps_AppID DEFAULT (NEWID())
	,CONSTRAINT PK_Apps PRIMARY KEY NONCLUSTERED (AppID)

	,AppName NVARCHAR(100) NOT NULL
	,INDEX IX_Apps_AppName (AppName)

	,CreateDate DATETIME2 NOT NULL
		CONSTRAINT DF_Apps_AppName DEFAULT (SYSUTCDATETIME())
	,INDEX IX_Apps_CreateDate (CreateDate)
);
GO